"""Tests for the projection of a trade log onto the two return series.

The four kinds required by ``04`` are present and labelled by class:

``TestAnalyticCases``
    Closed form results: the dilution identity of ``02`` section 1.6, the
    single non zero period collapsing to ``1/sqrt(T)``, and the algebraic
    equivalence of the two readings of the ``CURRENT_EQUITY`` composition rule.

``TestInvariances``
    Scale, translation and within period permutation.

``TestDegenerateCases``
    Empty log, one trade, all winners, all losers, scratch trade, ruin,
    calendar not covering the log, empty feasible set, forced grid.

``TestSyntheticRecovery``
    Data generated by a process with declared parameters, seed fixed, and the
    parameters recovered from the projection within sampling error.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta

import numpy as np
import pytest

from qvalid.adapters.calendars import WEEKDAYS_UTC_ID, weekdays_utc
from qvalid.adapters.validation import validate_trade_log
from qvalid.contracts import Basis, Period, Side, TradeLog, TradingCalendar, to_utc_nanos
from qvalid.core.constants import (
    MIN_ACTIVE_FRACTION,
    MIN_PERIODS,
    MONTHS_PER_YEAR,
    WEEKS_PER_YEAR,
    dilution_ratio_per_period,
)
from qvalid.core.gridding import (
    LADDER,
    GridSelection,
    period_returns,
    running_equity,
    select_grid,
    trade_returns,
)
from qvalid.exceptions import (
    CalendarCoverageError,
    GridSparsityError,
    InsufficientSampleError,
    TradeIntegrityError,
)

HOUR_NS = 3_600 * 1_000_000_000
DAY_NS = 24 * HOUR_NS
CAPITAL = 100_000.0
TICK = {"ES": 0.25}
MULTIPLIER = 50.0


def build_log(
    exits: list[datetime],
    pnl: np.ndarray,
    *,
    holding: timedelta = timedelta(hours=3),
    fees: float = 0.0,
) -> TradeLog:
    """Build a log whose prices are consistent with the supplied P&L.

    Exit prices are solved from the coherence identity of ``01``, so every log
    produced here also passes ``validate_trade_log``. Tests that need an
    invalid log construct it explicitly instead.
    """
    n = len(exits)
    assert pnl.shape == (n,)
    exit_ns = to_utc_nanos(exits)
    entry_ns = exit_ns - int(holding.total_seconds() * 1_000_000_000)
    side = np.full(n, int(Side.LONG), dtype=np.int8)
    qty = np.ones(n, dtype=np.float64)
    multiplier = np.full(n, MULTIPLIER, dtype=np.float64)
    fee_col = np.full(n, fees, dtype=np.float64)
    entry_px = np.full(n, 5_000.0, dtype=np.float64)
    exit_px = entry_px + (pnl + fee_col) / (qty * multiplier)
    return TradeLog(
        trade_id=np.array([f"t{i:05d}" for i in range(n)]),
        symbol=np.array(["ES"] * n),
        side=side,
        qty=qty,
        multiplier=multiplier,
        entry_ns=entry_ns,
        exit_ns=exit_ns,
        entry_px=entry_px,
        exit_px=exit_px,
        fees=fee_col,
        pnl=np.array(pnl, dtype=np.float64),
    )


def weekday_sequence(start: datetime, count: int, *, at_hour: int = 14) -> list[datetime]:
    """First ``count`` weekdays at or after ``start``, stamped at ``at_hour`` UTC."""
    out: list[datetime] = []
    day = start
    while len(out) < count:
        if day.weekday() < 5:
            out.append(day.replace(hour=at_hour, minute=0, second=0, microsecond=0))
        day += timedelta(days=1)
    return out


def sentinel_calendar(first: datetime, last: datetime) -> TradingCalendar:
    """Sentinel calendar padded a week on each side of the requested span."""
    return weekdays_utc(first - timedelta(days=7), last + timedelta(days=7))


class TestTradeReturns:
    def test_fixed_initial_is_pnl_over_capital(self) -> None:
        exits = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 5)
        pnl = np.array([100.0, -50.0, 0.0, 250.0, -25.0])
        log = build_log(exits, pnl)
        out = trade_returns(log, basis=Basis.FIXED_INITIAL, initial_capital=CAPITAL)
        np.testing.assert_allclose(out.values, pnl / CAPITAL)
        assert out.n_trades == 5

    def test_current_equity_compounds_to_final_equity(self) -> None:
        exits = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 20)
        rng = np.random.default_rng(1)
        pnl = rng.normal(200.0, 1_500.0, 20)
        log = build_log(exits, pnl)
        out = trade_returns(log, basis=Basis.CURRENT_EQUITY, initial_capital=CAPITAL)
        assert np.prod(1.0 + out.values) == pytest.approx(
            (CAPITAL + pnl.sum()) / CAPITAL, rel=1e-12
        )

    def test_values_are_read_only(self) -> None:
        exits = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 3)
        out = trade_returns(
            build_log(exits, np.array([1.0, 2.0, 3.0])),
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        with pytest.raises(ValueError, match="read-only"):
            out.values[0] = 0.0

    def test_running_equity_starts_at_capital_and_ends_at_final(self) -> None:
        exits = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 4)
        pnl = np.array([10.0, -3.0, 7.0, 1.0])
        equity = running_equity(build_log(exits, pnl), CAPITAL)
        assert equity.size == 5
        assert equity[0] == CAPITAL
        assert equity[-1] == pytest.approx(CAPITAL + pnl.sum())


class TestAnalyticCases:
    def test_dilution_identity_is_exact_under_the_projection(self) -> None:
        """``02`` section 1.6, per period form, recovered end to end.

        The identity ``var_grid = p * var_a + p * (1 - p) * mu_a^2`` is exact
        for the sample when the inactive periods are exactly zero, so with
        population variance the recovered ratio must match the closed form to
        floating point, not merely within sampling error. Any discrepancy is a
        bug in the attribution, not noise.
        """
        rng = np.random.default_rng(11)
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 400)
        active_idx = np.sort(rng.choice(len(days), size=100, replace=False))
        pnl = rng.normal(400.0, 1_200.0, active_idx.size)
        log = build_log([days[i] for i in active_idx], pnl)
        cal = sentinel_calendar(days[0], days[-1])

        grid = period_returns(
            log, cal, period=Period.DAILY, basis=Basis.FIXED_INITIAL, initial_capital=CAPITAL
        )
        values = np.asarray(grid.values)
        active = values[values != 0.0]
        p = grid.active_fraction
        s_active = active.mean() / active.std(ddof=0)
        s_grid = values.mean() / values.std(ddof=0)

        assert s_grid / s_active == pytest.approx(
            dilution_ratio_per_period(p, float(s_active)), rel=1e-12
        )
        assert s_grid < s_active

    def test_single_non_zero_period_gives_one_over_sqrt_t(self) -> None:
        """``02`` section 1.6, degenerate case, exact for any magnitude.

        The grid is trimmed to the trades, so producing ``T`` periods with a
        single non zero return needs a scratch trade anchoring the near end.
        That is not a contrivance: it is the only way the case arises once the
        grid extent is a function of the log.
        """
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 80)
        cal = sentinel_calendar(days[0], days[-1])
        for magnitude in (0.01, 1e6):
            log = build_log([days[0], days[-1]], np.array([0.0, magnitude]))
            grid = period_returns(
                log, cal, period=Period.DAILY, basis=Basis.FIXED_INITIAL, initial_capital=CAPITAL
            )
            t = grid.n_periods
            values = np.asarray(grid.values)
            sharpe = values.mean() / values.std(ddof=1)
            assert sharpe == pytest.approx(1.0 / np.sqrt(t), rel=1e-10)
            annual = sharpe * np.sqrt(grid.periods_per_year)
            assert annual == pytest.approx(1.0 / np.sqrt(grid.years), rel=1e-10)

    def test_current_equity_period_return_equals_within_period_compounding(self) -> None:
        """The two readings of the ``01`` composition rule coincide exactly."""
        rng = np.random.default_rng(3)
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 120)
        exits = [d for d in days for _ in range(3)]
        pnl = rng.normal(150.0, 900.0, len(exits))
        log = build_log(exits, pnl)
        cal = sentinel_calendar(days[0], days[-1])
        grid = period_returns(
            log, cal, period=Period.WEEKLY, basis=Basis.CURRENT_EQUITY, initial_capital=CAPITAL
        )
        per_trade = trade_returns(log, basis=Basis.CURRENT_EQUITY, initial_capital=CAPITAL)
        assert np.prod(1.0 + np.asarray(grid.values)) == pytest.approx(
            np.prod(1.0 + np.asarray(per_trade.values)), rel=1e-12
        )

    def test_fixed_initial_conserves_total_pnl_on_every_rung(self) -> None:
        rng = np.random.default_rng(5)
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 250)
        pnl = rng.normal(0.0, 800.0, len(days))
        log = build_log(days, pnl)
        cal = sentinel_calendar(days[0], days[-1])
        for rung in LADDER:
            grid = period_returns(
                log, cal, period=rung, basis=Basis.FIXED_INITIAL, initial_capital=CAPITAL
            )
            assert float(np.asarray(grid.values).sum()) * CAPITAL == pytest.approx(
                pnl.sum(), rel=1e-10
            )

    def test_weekly_edges_are_sunday_end_of_day_utc(self) -> None:
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 30)
        log = build_log(days, np.zeros(len(days)))
        cal = sentinel_calendar(days[0], days[-1])
        grid = period_returns(
            log, cal, period=Period.WEEKLY, basis=Basis.FIXED_INITIAL, initial_capital=CAPITAL
        )
        edges = np.asarray(grid.period_end_ns).astype("datetime64[ns]")
        for edge in edges:
            stamp = edge.astype("datetime64[us]").astype(datetime).replace(tzinfo=UTC)
            assert stamp.weekday() == 6
            assert (stamp.hour, stamp.minute, stamp.second) == (23, 59, 59)

    def test_periods_per_year_source_by_rung(self) -> None:
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 300)
        log = build_log(days, np.zeros(len(days)))
        cal = sentinel_calendar(days[0], days[-1])
        rates = {
            rung: period_returns(
                log, cal, period=rung, basis=Basis.FIXED_INITIAL, initial_capital=CAPITAL
            ).periods_per_year
            for rung in LADDER
        }
        assert rates[Period.DAILY] == cal.sessions_per_year()
        assert rates[Period.WEEKLY] == WEEKS_PER_YEAR
        assert rates[Period.MONTHLY] == MONTHS_PER_YEAR

    def test_sentinel_session_rate_matches_the_declared_constant(self) -> None:
        """``WEEKDAYS_PER_YEAR`` is the rate the sentinel actually realises."""
        cal = weekdays_utc(datetime(2010, 1, 1, tzinfo=UTC), datetime(2030, 1, 1, tzinfo=UTC))
        from qvalid.core.constants import WEEKDAYS_PER_YEAR

        assert cal.sessions_per_year() == pytest.approx(WEEKDAYS_PER_YEAR, rel=1e-3)
        assert cal.calendar_id == WEEKDAYS_UTC_ID


class TestInvariances:
    def test_scale_invariance_of_returns(self) -> None:
        rng = np.random.default_rng(13)
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 150)
        pnl = rng.normal(100.0, 700.0, len(days))
        cal = sentinel_calendar(days[0], days[-1])
        base = period_returns(
            build_log(days, pnl),
            cal,
            period=Period.DAILY,
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        scaled = period_returns(
            build_log(days, pnl * 7.5),
            cal,
            period=Period.DAILY,
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL * 7.5,
        )
        np.testing.assert_allclose(np.asarray(base.values), np.asarray(scaled.values), rtol=1e-12)

    def test_within_period_permutation_leaves_fixed_initial_unchanged(self) -> None:
        rng = np.random.default_rng(17)
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 90)
        exits = [d for d in days for _ in range(4)]
        pnl = rng.normal(0.0, 500.0, len(exits))
        cal = sentinel_calendar(days[0], days[-1])
        original = period_returns(
            build_log(exits, pnl),
            cal,
            period=Period.DAILY,
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        shuffled = pnl.reshape(-1, 4)[:, ::-1].reshape(-1).copy()
        permuted = period_returns(
            build_log(exits, shuffled),
            cal,
            period=Period.DAILY,
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        np.testing.assert_allclose(
            np.asarray(original.values), np.asarray(permuted.values), rtol=1e-12
        )

    def test_whole_week_translation_leaves_the_weekly_grid_unchanged(self) -> None:
        rng = np.random.default_rng(19)
        days = weekday_sequence(datetime(2024, 1, 8, tzinfo=UTC), 120)
        pnl = rng.normal(0.0, 400.0, len(days))
        shifted = [d + timedelta(days=7) for d in days]
        first = period_returns(
            build_log(days, pnl),
            sentinel_calendar(days[0], days[-1]),
            period=Period.WEEKLY,
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        second = period_returns(
            build_log(shifted, pnl),
            sentinel_calendar(shifted[0], shifted[-1]),
            period=Period.WEEKLY,
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        assert first.n_periods == second.n_periods
        assert first.n_active == second.n_active
        np.testing.assert_allclose(np.asarray(first.values), np.asarray(second.values), rtol=1e-12)

    def test_coarsening_is_monotone_in_active_fraction(self) -> None:
        rng = np.random.default_rng(23)
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 500)
        active = np.sort(rng.choice(len(days), size=60, replace=False))
        log = build_log([days[i] for i in active], rng.normal(0.0, 900.0, active.size))
        cal = sentinel_calendar(days[0], days[-1])
        fractions = [
            period_returns(
                log, cal, period=rung, basis=Basis.FIXED_INITIAL, initial_capital=CAPITAL
            ).active_fraction
            for rung in LADDER
        ]
        assert fractions == sorted(fractions)


class TestDegenerateCases:
    def _empty_log(self) -> TradeLog:
        return TradeLog(
            trade_id=np.array([], dtype="<U1"),
            symbol=np.array([], dtype="<U1"),
            side=np.array([], dtype=np.int8),
            qty=np.array([], dtype=np.float64),
            multiplier=np.array([], dtype=np.float64),
            entry_ns=np.array([], dtype=np.int64),
            exit_ns=np.array([], dtype=np.int64),
            entry_px=np.array([], dtype=np.float64),
            exit_px=np.array([], dtype=np.float64),
            fees=np.array([], dtype=np.float64),
            pnl=np.array([], dtype=np.float64),
        )

    def test_empty_log_is_refused_with_a_typed_error(self) -> None:
        with pytest.raises(InsufficientSampleError, match="empty TradeLog"):
            trade_returns(self._empty_log(), basis=Basis.FIXED_INITIAL, initial_capital=CAPITAL)

    def test_single_trade_gives_a_single_active_period(self) -> None:
        day = weekday_sequence(datetime(2024, 3, 4, tzinfo=UTC), 1)
        log = build_log(day, np.array([500.0]))
        grid = period_returns(
            log,
            sentinel_calendar(day[0], day[0]),
            period=Period.DAILY,
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        assert grid.n_periods == 1
        assert grid.n_active == 1
        assert grid.active_fraction == 1.0

    def test_single_period_grid_falls_back_to_the_nominal_period_length(self) -> None:
        """With one period there is no observed spacing, so the ladder needs a nominal one."""
        day = weekday_sequence(datetime(2024, 3, 4, tzinfo=UTC), 1)
        log = build_log(day, np.array([500.0]))
        with pytest.raises(GridSparsityError):
            select_grid(
                log,
                sentinel_calendar(day[0], day[0]),
                basis=Basis.FIXED_INITIAL,
                initial_capital=CAPITAL,
            )
        forced = select_grid(
            log,
            sentinel_calendar(day[0], day[0]),
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
            forced_period=Period.DAILY,
        )
        assert forced.candidates[0].n_periods == 1
        assert forced.candidates[0].holding_ratio == pytest.approx(3.0 / 24.0)

    @pytest.mark.parametrize("sign", [1.0, -1.0])
    def test_all_winners_and_all_losers(self, sign: float) -> None:
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 100)
        pnl = np.full(len(days), sign * 250.0)
        grid = period_returns(
            build_log(days, pnl),
            sentinel_calendar(days[0], days[-1]),
            period=Period.DAILY,
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        values = np.asarray(grid.values)
        assert bool(np.all(np.sign(values) == sign))
        assert values.std(ddof=1) == pytest.approx(0.0, abs=1e-15)

    def test_scratch_trade_counts_as_active_but_returns_zero(self) -> None:
        """``n_active`` counts attribution, not non zero returns."""
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 10)
        pnl = np.zeros(len(days))
        pnl[0] = 100.0
        pnl[-1] = -100.0
        grid = period_returns(
            build_log(days, pnl),
            sentinel_calendar(days[0], days[-1]),
            period=Period.DAILY,
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        assert grid.n_active == grid.n_periods == 10
        assert int((np.asarray(grid.values) != 0.0).sum()) == 2

    def test_ruin_under_current_equity_is_refused_and_names_the_remedy(self) -> None:
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 3)
        log = build_log(days, np.array([-40_000.0, -70_000.0, 5_000.0]))
        with pytest.raises(TradeIntegrityError, match="FIXED_INITIAL") as excinfo:
            trade_returns(log, basis=Basis.CURRENT_EQUITY, initial_capital=CAPITAL)
        assert excinfo.value.observed <= 0.0
        assert excinfo.value.threshold == 0.0

    def test_ruin_under_fixed_initial_is_representable(self) -> None:
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 3)
        log = build_log(days, np.array([-40_000.0, -70_000.0, 5_000.0]))
        out = trade_returns(log, basis=Basis.FIXED_INITIAL, initial_capital=CAPITAL)
        assert float(np.asarray(out.values).sum()) < -1.0

    def test_non_positive_capital_is_refused(self) -> None:
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 2)
        log = build_log(days, np.array([1.0, 2.0]))
        with pytest.raises(TradeIntegrityError, match="initial_capital"):
            trade_returns(log, basis=Basis.FIXED_INITIAL, initial_capital=0.0)

    def test_calendar_ending_before_the_log_is_refused(self) -> None:
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 40)
        log = build_log(days, np.zeros(len(days)))
        short = weekdays_utc(days[0] - timedelta(days=7), days[20])
        with pytest.raises(CalendarCoverageError, match="ends before"):
            period_returns(
                log,
                short,
                period=Period.DAILY,
                basis=Basis.FIXED_INITIAL,
                initial_capital=CAPITAL,
            )

    def test_calendar_starting_after_the_log_is_refused(self) -> None:
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 40)
        log = build_log(days, np.zeros(len(days)))
        late = weekdays_utc(days[10], days[-1] + timedelta(days=7))
        with pytest.raises(CalendarCoverageError, match="starts after"):
            period_returns(
                log, late, period=Period.DAILY, basis=Basis.FIXED_INITIAL, initial_capital=CAPITAL
            )

    def test_empty_feasible_set_raises_and_explains_every_rung(self) -> None:
        """Sparse and long held: no rung works, for a different reason on each."""
        rng = np.random.default_rng(29)
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 400)
        active = np.sort(rng.choice(len(days), size=12, replace=False))
        log = build_log(
            [days[i] for i in active],
            rng.normal(0.0, 900.0, active.size),
            holding=timedelta(days=45),
        )
        cal = sentinel_calendar(days[0], days[-1])
        with pytest.raises(GridSparsityError) as excinfo:
            select_grid(log, cal, basis=Basis.FIXED_INITIAL, initial_capital=CAPITAL)
        message = str(excinfo.value)
        for rung in LADDER:
            assert str(rung) in message
        assert "MIN_ACTIVE_FRACTION" in message
        assert "MIN_PERIODS" in message

    def test_forced_grid_turns_rejections_into_warnings(self) -> None:
        rng = np.random.default_rng(31)
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 400)
        active = np.sort(rng.choice(len(days), size=12, replace=False))
        log = build_log([days[i] for i in active], rng.normal(0.0, 900.0, active.size))
        cal = sentinel_calendar(days[0], days[-1])
        selection = select_grid(
            log,
            cal,
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
            forced_period=Period.DAILY,
        )
        assert selection.forced is True
        assert selection.period is Period.DAILY
        assert selection.warnings
        assert all(w.startswith("forced grid") for w in selection.warnings)

    def test_forced_feasible_grid_produces_no_warning(self) -> None:
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 300)
        log = build_log(days, np.full(len(days), 10.0))
        cal = sentinel_calendar(days[0], days[-1])
        selection = select_grid(
            log,
            cal,
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
            forced_period=Period.WEEKLY,
        )
        assert selection.warnings == ()
        assert selection.period is Period.WEEKLY


class TestLadderRule:
    def test_finest_feasible_rung_wins(self) -> None:
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 300)
        log = build_log(days, np.full(len(days), 25.0))
        selection = select_grid(
            log,
            sentinel_calendar(days[0], days[-1]),
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        assert selection.period is Period.DAILY
        assert selection.candidates[0].feasible

    def test_long_holding_pushes_the_grid_off_daily(self) -> None:
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 400)
        log = build_log(days, np.full(len(days), 20.0), holding=timedelta(days=4))
        selection = select_grid(
            log,
            sentinel_calendar(days[0], days[-1]),
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        assert selection.period is Period.WEEKLY
        assert not selection.candidates[0].feasible
        assert any("MAX_HOLDING_TO_PERIOD" in r for r in selection.candidates[0].rejections)

    def test_sparsity_pushes_the_grid_off_daily(self) -> None:
        rng = np.random.default_rng(37)
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 600)
        active = np.sort(rng.choice(len(days), size=70, replace=False))
        log = build_log([days[i] for i in active], rng.normal(50.0, 600.0, active.size))
        selection = select_grid(
            log,
            sentinel_calendar(days[0], days[-1]),
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        assert selection.period is not Period.DAILY
        assert any("MIN_ACTIVE_FRACTION" in r for r in selection.candidates[0].rejections)

    def test_every_rung_is_diagnosed_even_after_the_winner(self) -> None:
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 300)
        log = build_log(days, np.full(len(days), 25.0))
        selection = select_grid(
            log,
            sentinel_calendar(days[0], days[-1]),
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        assert tuple(c.period for c in selection.candidates) == LADDER

    def test_selection_is_a_frozen_contract(self) -> None:
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 300)
        log = build_log(days, np.full(len(days), 25.0))
        selection = select_grid(
            log,
            sentinel_calendar(days[0], days[-1]),
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        assert isinstance(selection, GridSelection)
        with pytest.raises((AttributeError, TypeError)):
            selection.forced = True  # type: ignore[misc]


class TestSyntheticRecovery:
    def test_bernoulli_arrival_rate_is_recovered_in_the_active_fraction(self) -> None:
        """Arrivals generated at a declared rate, recovered from the projection."""
        rng = np.random.default_rng(101)
        days = weekday_sequence(datetime(2020, 1, 1, tzinfo=UTC), 2_000)
        p_true = 0.30
        drawn = rng.random(len(days)) < p_true
        drawn[0] = drawn[-1] = True
        idx = np.flatnonzero(drawn)
        log = build_log([days[i] for i in idx], rng.normal(300.0, 1_100.0, idx.size))
        grid = period_returns(
            log,
            sentinel_calendar(days[0], days[-1]),
            period=Period.DAILY,
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        standard_error = np.sqrt(p_true * (1 - p_true) / len(days))
        assert abs(grid.active_fraction - p_true) < 4.0 * standard_error

    def test_declared_edge_is_recovered_in_the_grid_mean(self) -> None:
        """Mean P&L per period recovered from a process with a declared mean."""
        rng = np.random.default_rng(103)
        days = weekday_sequence(datetime(2020, 1, 1, tzinfo=UTC), 1_500)
        mu, sigma = 250.0, 900.0
        pnl = rng.normal(mu, sigma, len(days))
        grid = period_returns(
            build_log(days, pnl),
            sentinel_calendar(days[0], days[-1]),
            period=Period.DAILY,
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        values = np.asarray(grid.values)
        standard_error = sigma / CAPITAL / np.sqrt(len(days))
        assert abs(values.mean() - mu / CAPITAL) < 4.0 * standard_error

    def test_ladder_choice_is_stable_across_seeds_for_a_declared_process(self) -> None:
        """The rule must not flip rung on resampling noise alone."""
        days = weekday_sequence(datetime(2020, 1, 1, tzinfo=UTC), 1_000)
        cal = sentinel_calendar(days[0], days[-1])
        chosen = set()
        for seed in range(201, 211):
            rng = np.random.default_rng(seed)
            drawn = rng.random(len(days)) < 0.40
            drawn[0] = drawn[-1] = True
            idx = np.flatnonzero(drawn)
            log = build_log([days[i] for i in idx], rng.normal(200.0, 1_000.0, idx.size))
            chosen.add(
                select_grid(log, cal, basis=Basis.FIXED_INITIAL, initial_capital=CAPITAL).period
            )
        assert chosen == {Period.DAILY}

    def test_thresholds_are_the_ones_the_constants_declare(self) -> None:
        """Guards against a threshold drifting away from its written derivation."""
        assert MIN_ACTIVE_FRACTION == 0.15
        assert MIN_PERIODS == 60


class TestBoundaryIntegration:
    def test_a_validated_log_grids_without_further_checks(self) -> None:
        """The boundary validates, ``core`` projects. No revalidation in between."""
        rng = np.random.default_rng(211)
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 260)
        log = build_log(days, rng.normal(150.0, 800.0, len(days)), fees=4.2)
        validate_trade_log(log, tick_size=TICK)
        selection = select_grid(
            log,
            sentinel_calendar(days[0], days[-1]),
            basis=Basis.FIXED_INITIAL,
            initial_capital=CAPITAL,
        )
        assert selection.period is Period.DAILY
        assert selection.returns.calendar_id == WEEKDAYS_UTC_ID
        assert selection.returns.basis is Basis.FIXED_INITIAL

    def test_post_close_exit_lands_in_the_next_session(self) -> None:
        """A fill after the close belongs to the following session, not to this one."""
        days = weekday_sequence(datetime(2024, 1, 2, tzinfo=UTC), 5, at_hour=22)
        log = build_log(days[:1], np.array([1_000.0]))
        cal = sentinel_calendar(days[0], days[-1])
        grid = period_returns(
            log, cal, period=Period.DAILY, basis=Basis.FIXED_INITIAL, initial_capital=CAPITAL
        )
        edge = int(np.asarray(grid.period_end_ns)[0])
        assert edge > int(np.asarray(log.exit_ns)[0])
        assert (edge - int(np.asarray(log.exit_ns)[0])) < 24 * HOUR_NS
